# This is a basic workflow to help you get started with Actions

name: Build facebody-20191230 C++ SDK

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env: 
      CPLUS_INCLUDE_PATH: "/usr/local/include/:/usr/include/jsoncpp/:/usr/lib/"
    steps:
      - uses: actions/checkout@v2

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v7.1
        with:
          # Just install vcpkg for now, do not install any ports in this step yet.
          setupOnly: true

      - name: Run CMake to install the dependencies specified in the vcpkg.json manifest, generate project file and build the project
        uses: lukka/run-cmake@v3

      - name: Install dependencies
        run: |
          vcpkg install boost
          vcpkg install cpprestsdk
          vcpkg install openssl-windows
          vcpkg install jsoncpp
      
      - name: Build facebody c++ sdk
        run: |
          git clone https://github.com/alibabacloud-sdk-cpp/facebody-20191230.git
          cd facebody-20191230 && rm -rf cmake_build/
          mkdir -p cmake_build/ && cd cmake_build/
          cmake .. -DENABLE_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/../../install/
          cmake --build . --target install

      # - name: Save build result
      #   run: |
      #     rm -rf facebody-20191230/
      #     git config --global user.email "axioscros@aliyun.com"
      #     git config --global user.name "AxiosCros"
      #     git remote rm origin
      #     git remote add origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
      #     git add ./install/ -f
      #     git checkout -b build/facabody-cpp-sdk
      #     git commit -m "Build facebody-20191230 C++ SDK"
      #     git push --force --set-upstream origin build/facabody-cpp-sdk
